---
- hosts: bobbins


  pre_tasks:
  - include: tasks/x.yml

  roles:
    - bogus
    - hello
    - { role: morecomplex, t: z }

  tasks:
  - include: tasks/x.yml
  - include: tasks/x.yml

  handlers:
  - include: handlers/y.yml

- include: play.yml

